/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as UsersIndexRouteImport } from './pages/users/index'
import { Route as NotfoundIndexRouteImport } from './pages/notfound/index'
import { Route as LoginIndexRouteImport } from './pages/login/index'
import { Route as HomeIndexRouteImport } from './pages/home/index'

const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotfoundIndexRoute = NotfoundIndexRouteImport.update({
  id: '/notfound/',
  path: '/notfound/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/home/': typeof HomeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/notfound/': typeof NotfoundIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeIndexRoute
  '/login': typeof LoginIndexRoute
  '/notfound': typeof NotfoundIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home/': typeof HomeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/notfound/': typeof NotfoundIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home/' | '/login/' | '/notfound/' | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/login' | '/notfound' | '/users'
  id: '__root__' | '/home/' | '/login/' | '/notfound/' | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  NotfoundIndexRoute: typeof NotfoundIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notfound/': {
      id: '/notfound/'
      path: '/notfound'
      fullPath: '/notfound/'
      preLoaderRoute: typeof NotfoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  NotfoundIndexRoute: NotfoundIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
